name: remark_app
description: Online Job

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2.8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  splashscreen: ^1.3.5
  introduction_screen: ^2.1.0
  modal_bottom_sheet: ^3.0.0-pre
  shared_preferences: ^2.0.5
  extended_image: ^4.1.0
  http: ^0.13.3
  firebase_core: ^2.1.1
  firebase_core_platform_interface: 4.5.2
  firebase_messaging: 14.0.4
  flutter_local_notifications: 12.0.0
  persistent_bottom_nav_bar: ^4.0.2
  fl_chart: ^0.36.1
  infinite_scroll_pagination: 3.0.1+1
  google_fonts: ^2.1.0
  pinput: ^2.2.21
  code_fields: ^0.0.3
  google_sign_in: ^6.1.0
  firebase_auth: ^4.1.1
  shimmer: ^2.0.0
  timeago: ^3.0.2
  share: ^2.0.4
  like_button: ^2.0.2
  avatar_glow: ^2.0.1
  url_launcher: ^6.0.4
  dio: ^4.0.0
  permission_handler: ^10.2.0
  path_provider:
  chat_bubbles: ^1.0.0+3
  contained_tab_bar_view: ^0.7.1
  flutter_advanced_switch: ^2.1.0
  flutter_swiper: ^1.1.6
  flutter_webrtc: ^0.9.26
  sdp_transform: ^0.3.0
  image_picker: 0.8.0+4
  awesome_select: ^6.0.0
  flutter_tags: ^0.4.9+1
  google_place: ^0.4.0
  file_picker: ^3.0.3
  liquid_pull_to_refresh: ^3.0.0
  provider: ^5.0.0
  quick_actions: ^0.6.0+2
  rive_splash_screen: ^0.1.0
  tutorial_coach_mark: ^1.0.3
  rive: ^0.7.22
  socket_io_client: ^2.0.0
  connectivity_plus: 2.3.6+1
  flutter_svg: ^0.22.0
  open_file_safe: ^3.2.1
  firebase_dynamic_links: ^5.0.4
  sign_in_with_apple: ^4.1.0
  in_app_update: 3.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_launcher_icons: 
  dropdown_search: ^5.0.6
  image_cropper:
 
dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "assets/logo/logo.png" 
  android: true
  ios: true
  remove_alpha_ios: true
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/flag/
    - assets/icons/
    - assets/splash/
    - assets/onboarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
